### ISSUE TITLE
StartScreen opens, but event handler does not work

### ISSUE THREAD

**Issue by Bamagik** [axk4545/hfoss-sugar-snake#11]
The pygame event catcher does not seem to notice any keydown button press. I'll try to take a look at it tomorrow night when I get home from work. I'm going to design an actual image for the background in the meantime.

**Comment by axk4545** [comment]
It only recognizes arrow keys since it runs as a sugar activity and uses
window buttons instead of Q. Please don't change that. It took so long to
do.

**Comment by axk4545** [comment]
@Bamagik I added the button and the code to react to it. I am not sure what is going on. See lines 195-203 in mainGame.py and 56-60 and 84-85 in snakeActivity.py

**Comment by axk4545** [comment]
@Bamagik I am currently in a bio lab but I think I just solved it in my
head. I will add the changes around noon.

Also the start screen draft looks great.
Please add to assets.

**Comment by axk4545** [comment]
Play button now works. I can't get the blit to work right for the start screen. If I remove it though, the rest of the game works.

**Comment by axk4545** [comment]
@Bamagik I got thebackground but it doesn't quite scale right. do we want to restrict the screen size?

**Comment by Bamagik** [comment]
I can rescale it if you give me measurements for the screen. When I get home

**Comment by axk4545** [comment]
@Bamagik I don't know how to get the screen size since this is going to run on a variety of devices. Any ideas? Maybe it can use an SVG?

**Comment by axk4545** [comment]
Working.
