### ISSUE TITLE
Final Prototype Submission

### ISSUE THREAD

**Issue by gen1e** [axk4545/hfoss-sugar-snake#17]
Tag it as a prototype in git. We probably want to compose a blogpost of the current state of the project. I can probably help out by making a quick screen cap of our current working prototype tomorrow.

**Comment by axk4545** [comment]
@gen1e @CalvinWu4 @Bamagik tag is done. Blog is still needed

**Comment by Bamagik** [comment]
I believe I may have linked this in irc, But I will also put it here, and close this issue.
http://qar4778-hfoss.blogspot.com/2018/04/final-project-prototype-and-update.html
