### ISSUE TITLE
Randomization is broken

### ISSUE THREAD

**Issue by axk4545** [axk4545/hfoss-sugar-snake#21]
The randomization for the multiplication problems does not work. The same problem is shown multiple times in a row. I made you a branch `randomization-pause` to work in. You can also use this to reimplement the pause function you wanted. I suggest using the spacebar for that. Please test before pushing as always.

**Comment by axk4545** [comment]
I tested the newest changes and they didn't seem to fix the bug. Please test  in Sugar to double check that I am not crazy.

**Comment by gen1e** [comment]
Fixed as of 897f944b3526deac6388be921af31f6543b6975a
