### ISSUE TITLE
Assets for game

### ISSUE THREAD

**Issue by gen1e** [axk4545/hfoss-sugar-snake#4]
We want to have our own assets to make the game more our own. Things we need to make:

[x] Background
[x] Snake Head
[x] Snake body
[x] Snake tail
[x] Blocks/food for eating (will have a number on them)

**Comment by Bamagik** [comment]
![sugar-project](https://user-images.githubusercontent.com/14032450/38849231-485f9dba-41d9-11e8-9731-632b94cd1820.png)

How does this look for a prototype start screen?

**Comment by axk4545** [comment]
Beautiful. I will see if I can add a play button to the window tomorrow to
allow us to start the game. I will give it a  delay. 10 seconds good?

**Comment by gen1e** [comment]
I think this is it for the head, working on the body and tail next.
![snake-head](https://user-images.githubusercontent.com/15071353/38894955-b6591192-425c-11e8-9b0c-0bea9424cdc5.png)

**Comment by axk4545** [comment]
@gen1e awww I love it! :)

**Comment by axk4545** [comment]
Maybe scale it down a little.

**Comment by gen1e** [comment]
Yea np, I was going to see how big the things were and then it's easy to scale down. I know the originals were waaay too small. Once I'm done with the tail I'll start messing with the sizes.

**Comment by axk4545** [comment]
```
        self.snakeimg = pygame.image.load(path.join(assets + '/snake.png'))
        self.snakebody = pygame.image.load(path.join(assets + '/body.png'))
        self.snaketail = pygame.image.load(path.join(assets + '/tail.png'))
        self.gameicon = pygame.image.load(path.join(assets + '/gameicon.png'))
        self.appleimg = pygame.image.load(path.join(assets + '/apple.png'))
        self.startScreen = pygame.image.load(path.join(assets + '/start-screen.png'))
```

**Comment by axk4545** [comment]
`snakeimg` is the head

**Comment by axk4545** [comment]
@gen1e @Bamagik I think this is done. If so please close as confirmation.

**Comment by gen1e** [comment]
I think we have everything for this
