### ISSUE TITLE
Failing to install xo file - need to fix the activity.py

### ISSUE THREAD

**Issue by gen1e** [axk4545/hfoss-sugar-snake#6]
Following the steps on the [quickstart](https://github.com/FOSSRIT/sugar-quickstart#building--distributing) for building the xo file and ran:

    sugar-install-bundle example-1.xo

With the results:
![screenshot](https://user-images.githubusercontent.com/15071353/38621327-a7fdb0f0-3d6e-11e8-9949-7287c8905f3a.png)

It doesn't show up in the activities. When trying to run with

    sugar-launch example-1

It can't find it.

**Comment by axk4545** [comment]
<axk4545> how can I launch a python script inside a sugar activity window?
13:49 <Pro-Panda> axk4545: You can run Python scripts in the Pippy Activity
13:51 <axk4545> Pro-Panda: I am asking about writing my own activity and where to call my code so it will launch in the Activity window
13:51 <walterbender> axk4545, you can also use Pippy to create a new Sugar activity for you that will run your script.
13:51 <axk4545> walterbender: oh? cool.
13:52 <walterbender> that's the easiest way to get started. it is one of the export options
13:52 <axk4545> walterbender: ok

**Comment by gen1e** [comment]
@axk4545 This is what I got with what you just pushed
![screenshot_2018-04-12_22-13-26](https://user-images.githubusercontent.com/15071353/38713393-f1593b9e-3e9e-11e8-81f1-c4d9438fa470.png)

**Comment by gen1e** [comment]
Aidan is still working on it on the activity branch, progress has been made in understanding how the activity.py works and how to incorporate the Plaked code into it.

**Comment by axk4545** [comment]
This has been fixed.
